version: '3.8'

services:
  app:
    build: .
    container_name: node-app
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=yourusername
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdb
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

  dashboard:
    container_name: dashboard
    build:
      context: ./dashboard  # Specify the path to the Dockerfile for the dashboard
      dockerfile: Dockerfile
    ports:
      - '3001:80'  # Expose port 80 from the Nginx container to port 3001 on the host
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

  redis:
    image: 'redis:alpine'
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - app-network

  postgres:
    image: 'postgres:13'
    container_name: postgres
    environment:
      - POSTGRES_USER=yourusername
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
